# Databricks notebook source
tables_list = [
    "CFG_SFDC_PREMERGE_FIELDS",
    "IST_PS_STEPS_PRE_ALIGNMENT",
    "IST_PS_UPDATES_PRE_ALIGNMENT",
    "Incremental_Account",
    "ZZ_BK_BULK_DCR_TAR1650",
    "IST_PS_STEPS_ALIGNMENT",
    "IST_MDM_STATUS",
    "IST_ACCOUNT_PREMERGE_HISTORY",
    "IST_CFG_SFDC_TEAM_ALIGNMENT_CURR",
    "IST_DW_ALIGNMENT_ID_MAP_CURR",
    "CFG_SFDC_BULK_INSERT_ACCOUNTS",
    "IST_PROF_UNIVERSE_ADDITION_TARGETS_20231221",
    "IST_SELF_ALIGNS_TO_DROP_History",
    "IST_INACTIVE_SFA_TERRS_CURR",
    "CFG_SFDC_MAPPING",
    "IST_UNASSIGN_TERRS_CURR",
    "IST_SFA_ALIGNMENT_VIEW_CURR",
    "IST_SFA_ALIGNMENT_ACTUAL_CURR",
    "CFG_SFDC_MAPPING_XREF",
    "IST_SFA_ALIGNMENT_ACCOUNTS_CURR",
    "IST_DW_CUSTOMER_ALIGNMENT_CURR",
    "IST_PS_STEPS_SYNC_OUTBOX_History",
    "IST_DW_ALIGNMENT_CURR",
    "CFG_INT_SETTINGS",
    "IST_PS_UPDATES_ALIGNMENT",
    "IST_MDM_SFA_DATA_CHANGE_REQUEST",
    "IST_PS_UPDATES_SYNC_OUTBOX_History",
    "Data_Change_Request_vod__History_Full",
    "IST_PS_STEPS_PRE_SYNC_OUTBOX",
    "IST_PS_UPDATES_POST_FULL_DOWNLOAD_History",
    "ACCOUNT_PREMERGE_UPDATE_PERSON",
    "Account_OBJECT_SYNC",
    "IST_PS_UPDATES_PRE_SYNC_OUTBOX",
    "IST_STAGE_DCR_TERR_MISMATCH",
    "Data_Change_Request_Line_vod__c_AutoActionID",
    "IST_ONEKEY_PROF_UNIVERSE_ADDITION",
    "IST_PS_STEPS_ATTRIBUTE_SYNC",
    "Data_Change_Request_vod__c_AutoMDM",
    "IST_STAGE_INSERT_SFA_IRD_PERSON",
    "EntityDefinitionAsc",
    "IST_STAGE_INSERT_SFA_IRD_PERSON_HISTORY",
    "IST_PS_UPDATES_ATTRIBUTE_SYNC",
    "IST_PS_STEPS_SYNC_OUTBOX",
    "IST_STAGE_INSERT_SFA_IRD_ACCT_LOC",
    "tmpSFDCDeltaPerson",
    "IST_PS_STEPS_PRE_ALIGNMENT_History",
    "IST_STAGE_INSERT_SFA_IRD_ACCT_LOC_HISTORY",
    "Account_OKSubscriptionEmail_Update",
    "tmpSFDCDeltaAcctLoc",
    "EntityDefinitionDesc",
    "tmpSFDCDeltaMergeReq",
    "IST_TEST_VW_OT2A",
    "BCC_Account_Merge__c_Upsert9ce3b86613f444f5aad48d7eb69d9c30",
    "MDVIEW_SFA_IRD_CFG_MAPPING",
    "IST_PS_UPDATES_PRE_SYNC_OUTBOX_History",
    "MDVIEW_SFA_IRD_CFG_SETTINGS",
    "REF_SFDC_OBJECTS",
    "IST_PS_UPDATES_ADHOC",
    "BCC_Account_Merge__c_Upsert",
    "ObjectTerritory2Association_History",
    "Account_PROF_Upsert",
    "IST_PS_UPDATES_PRE_ALIGNMENT_History",
    "IST_PROF_UNIVERSE_ADDITION",
    "Address_vod__c_Upsert",
    "CFG_CUSTOM_SYNC_PROCESSES",
    "IST_PS_STEPS_POSTDW_CUSTOM_SYNC",
    "IST_PS_UPDATES_ALIGNMENT_History",
    "IST_DIM_SALES_FORCE_CURR_HISTORY",
    "TSF_vod__c_Attribute_Sync",
    "Data_Change_Request_vod__c_AutoMDM_History",
    "IST_PS_UPDATES_POSTDW_CUSTOM_SYNC",
    "REF_PROC_ERROR_LOG",
    "FieldPermissions",
    "Data_Change_Request_Line_vod__c_AutoMDM_History",
    "ZZ_BK_WPA_Approvals_TAR1498",
    "CFG_AUDIT_TABLE_LIST",
    "Account_PROF_Upsert_History",
    "IST_PS_STEPS_ATTRIBUTE_SYNC_History",
    "Account_Territory_Loader_vod__c_DROP_SELF_ALIGNS_History",
    "Account_tblAuditValue",
    "ACCOUNT_PREMERGE_UPDATE_PERSON_History",
    "Account_Territory_Loader_vod__c_tblAuditValue",
    "Call2_Discussion_vod__c",
    "DCR_Field_Type_vod__c",
    "Address_vod__c_tblAuditValue",
    "BCC_Account_Merge__c_tblAuditValue",
    "IST_PS_UPDATES_ATTRIBUTE_SYNC_History",
    "Group",
    "CFG_CUSTOM_SYNC_UPDATES",
    "Profile_tblAuditValue",
    "Medical_Discussion_vod__c",
    "CFG_SFDC_TEAM_ALIGNMENT",
    "Territory2_tblAuditValue",
    "IST_PS_STEPS_POSTDW_CUSTOM_SYNC_History",
    "Product_vod__c",
    "Territory2Model_tblAuditValue",
    "Call2_Expense_vod__c",
    "Territory2Type_tblAuditValue",
    "FieldDefinition",
    "IST_SELF_ALIGNS_TO_DROP",
    "TSF_vod__c_tblAuditValue",
    "EntityParticle",
    "UserTerritory2Association_tblAuditValue",
    "GroupMember",
    "Product_Metrics_vod__c",
    "CFG_IST_DOWNLOAD",
    "AccountShare",
    "REF_SFA_DF_LOG",
    "Child_Account_vod__c",
    "IST_PS_STEPS_POST_FULL_DOWNLOAD_History",
    "CFG_SFDC_ALIGNMENT",
    "Data_Change_Request_Line_vod__c",
    "Clm_Presentation_Slide_vod__c",
    "TSF_vod__c",
    "Account_Merge_History_vod__c",
    "Account_Clone",
    "CFG_SFDC_ALIGNMENT_OUTBOUND",
    "REF_vwSFA_ACCT_TO_OT2A_ALIGNMENT",
    "Sent_Email_vod__c",
    "Call2_Key_Message_vod__c",
    "Account_List_vod__c",
    "IST_ADDITIONAL_TARGETS",
    "CFG_SFDC_ALIGNMENT_CLIENT_RULES",
    "IST_PS_STEPS_POST_SYNC_OUTBOX_History",
    "Territory2",
    "Key_Message_vod__c",
    "Medical_Inquiry_vod__c",
    "Time_Off_Territory_vod__c",
    "Call2_vod__c",
    "UserRole",
    "Time_Off_Territory_vod__c_SetApproved_History",
    "Call2_Detail_vod__c",
    "Approved_Document_vod__c",
    "IST_TARGET_UNIVERSE_ADDITION",
    "Data_Change_Request_vod__c_CorrectUserChange_20240911_2",
    "Account",
    "User_Detail_vod__c",
    "CFG_SFDC_MAPPING_AUDIT",
    "AsyncApexJob",
    "Approved_Email_Settings_vod__c",
    "GAS_Visibility_Configuration__c",
    "Call_Clickstream_vod__c",
    "Territory2Type",
    "PermissionSetAssignment",
    "RecordType",
    "PermissionSet",
    "IST_PS_STEPS_PRE_SYNC_OUTBOX_History",
    "DCR_Settings__c",
    "Network_Settings_vod__c",
    "User",
    "Account_List_Item_vod__c",
    "IST_TM1_TARGET_UNIVERSE_ADDITION",
    "Data_Change_Request_vod__c",
    "Territory2Model",
    "IST_PS_STEPS_ALIGNMENT_History",
    "AsyncApexJob",
    "Account_Territory_Loader_vod__c",
    "Approved_Email_Settings_vod__c",
    "GAS_Visibility_Configuration__c",
    "Call_Clickstream_vod__c",
    "Territory2Type",
    "PermissionSetAssignment",
    "RecordType",
    "PermissionSet",
    "IST_PS_STEPS_PRE_SYNC_OUTBOX_History",
    "DCR_Settings__c",
    "Network_Settings_vod__c",
    "User",
    "Account_List_Item_vod__c",
    "IST_TM1_TARGET_UNIVERSE_ADDITION",
    "Data_Change_Request_vod__c",
    "Territory2Model",
    "IST_PS_STEPS_ALIGNMENT_History",
    "Data_Change_Request_vod__c_CorrectUserChange_20240911",
    "Account_Territory_Loader_vod__c_SYNC_ALIGN_MEDICAL_AFFIARS",
    "Account_Territory_Loader_vod__c_SYNC_ALIGN_INSIDE_SALES",
    "CFG_SFDC_MAPPING_XREF_AUDIT",
    "Global_Account_Search_Settings_vod__c",
    "Profile",
    "CFG_ALIGNMENT_UPDATES_History",
    "BCC_Account_Merge__c",
    "AccountHistory",
    "CFG_ALIGNMENT_UPDATES",
    "Account_SyncMissingOneKeyIds",
    "IST_PS_UPDATES_POST_SYNC_OUTBOX",
    "Email_Activity_vod__c",
    "IST_PS_UPDATES_POSTDW_CUSTOM_SYNC_History",
    "CFG_SFDC_PREMERGE_FIELDS_AUDIT",
    "Territory2_20230526",
    "Veeva_Settings_vod__c",
    "IST_IS_DROP_OT2A_RESEARCH",
    "User_tblAuditValue",
    "TESTLOADHISTORY",
    "TESTLOADHISTORY_History",
    "Account_FixNPI",
    "Message_vod__c",
    "5_b253eac5dfb04a55995f4e412647c009_refresh",
    "Manual_Territory_Alignment_History_vod__c",
    "Territory_Settings_vod__c",
    "UserFieldAccess",
    "CFG_SFDC_PROCESS_SYNC",
    "5_c8299e1475264eb4b0bc3e8a20da8aaf_refresh",
    "CFG_SFDC_OBJECT_SYNC",
    "Data_Change_Request_vod__History",
    "ObjectTerritory2AssignmentRule",
    "Contact",
    "IST_PS_UPDATES_POST_SYNC_OUTBOX_History",
    "IST_PS_STEPS_POST_FULL_DOWNLOAD",
    "TSF_vod__c_Attribute_Sync_History",
    "CFG_TABLE_DOWNLOAD_AUDIT",
    "Account_SyncMissingOneKeyIds_History",
    "ObjectTerritory2Association_tblAuditValue",
    "Account_SyncUpdate_History",
    "IST_PS_UPDATES_POST_FULL_DOWNLOAD",
    "AccountHistory_Full",
    "Account_Territory_Loader_vod__c_Add_Update_CURR_History",
    "Account_Territory_Loader_vod__c_SYNC_ALIGN_ASSOCIATE_TERRITORY_LEADER_TerritoryDrop_History",
    "IST_SFA_ALIGNMENT_STAGE_OBJECT_NORMALIZED_CURR",
    "IST_SFA_STAGE_OBJECT_TERRS_TO_FIX_CURR",
    "Account_Territory_Loader_vod__c_Add_Update_CURR_History",
    "Account_Territory_Loader_vod__c_SYNC_ALIGN_ASSOCIATE_TERRITORY_LEADER_TerritoryDrop_History",
    "IST_SFA_ALIGNMENT_STAGE_OBJECT_NORMALIZED_CURR",
    "IST_SFA_STAGE_OBJECT_TERRS_TO_FIX_CURR",
    "CFG_TABLE_DOWNLOAD",
    "BCC_Account_Merge__c_InitialSeed_Cleanup",
    "Account_Territory_Loader_vod__c_SYNC_ALIGN_MEDICAL_AFFIARS_TerritoryAdd_History",
    "Account_Person_NewTypeDCR_AUTOCREATE",
    "ZZ_BK_DRI_TARSUS_TAR_1378",
    "Incremental_Territory2",
    "Data_Change_Request_Line_vod__c_AutoActionID_History",
    "Account_Territory_Loader_vod__c_ADD_UPSERT"
]

# COMMAND ----------

jdbcHostname = "tars-prd.database.windows.net"
database = "DW_PROD"
user = "TPITarsProcessManager"
password = "TPITkr@ProjeM8nkger"
jdbcPort = 1433
 
dbName = "db_sil_temp_delta"
 
# Loop through the tables_list
for tableName in tables_list:
    # Drop table if exists
    spark.sql(f"DROP TABLE IF EXISTS {dbName}.{tableName}")
    print(f"Dropped table: {tableName}")
 
for table in tables_list:
    # Read data from SQL Server
    sql_server_df = spark.read \
        .format("jdbc") \
        .option("url", f"jdbc:sqlserver://{jdbcHostname}:1433;databaseName={database};") \
        .option("databaseName", database) \
        .option("user", user) \
        .option("password", password) \
        .option("dbtable", f"sfa.{table}") \
        .load()
 
    # Write data to Delta table
    sql_server_df.write.option("compression","snappy").option("overwriteSchema", "true").option("mergeSchema", "true").mode("overwrite").format("delta").saveAsTable(f"db_sil_temp_delta.{table}")
 
    print(f"Created table: {table}")
